services:
  postgres:
    image: postgres:18-alpine
    container_name: eventbooker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eventbooker
      POSTGRES_PASSWORD: eventbooker
      POSTGRES_DB: eventbooker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local


